### ISSUE TITLE
Word wrap?

### ISSUE THREAD

**Issue by anilrdoshi** [docsteveharris/stata#1]
Steve,
First off, thanks very much for creating this Stata syntax file for Sublime Text. I have just started playing around with ST and it's great. Second, apologies for using this forum to make a suggestion / ask for help with your file. But I was not sure how to get in touch with you otherwise.

My question/issue:
I originally used the Textmate Stata bundle (off which you based your work) and I was getting lines to wrap in my window. Now with your file, the line does not wrap (soft wrap, I think it's called?). Is that a setting in ST I can change or is that something in your file that would have to be changed?

**Comment by docsteveharris** [comment]
Hi and thanks. Glad you found it useful. As far as I know it's just a menu setting in Sublime Text (View >> Word Wrap). S

**Comment by anilrdoshi** [comment]
Thanks very much for your response. I got it figured out.
